"""Browser checks for the isolated TestBrowserMusicSmoke fixture."""
import argparse
import tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--url', required=True, help='Isolated Go test fixture URL')
args = parser.parse_args()
output = Path(tempfile.mkdtemp(prefix='migi-music-browser-'))
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={'width': 1400, 'height': 1000})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(args.url)
    expect(page.locator('#library-list button')).to_have_count(2)
    assert page.evaluate('document.querySelector("audio").paused')
    page.get_by_role('button', name='Local album').click()
    expect(page.locator('#queue-list button')).to_have_count(2)
    page.wait_for_function('() => !document.querySelector("audio").paused && document.querySelector("audio").currentTime > 0.1')
    expect(page.locator('#track-title')).to_have_text('Local track')
    # Native audio controls drive these same browser playback operations.
    page.evaluate('document.querySelector("audio").pause()')
    expect(page.locator('#playback-status')).to_have_text('Пауза')
    page.evaluate('document.querySelector("audio").currentTime = 3')
    page.wait_for_function('() => Math.abs(document.querySelector("audio").currentTime - 3) < 0.2')
    page.locator('#next').click()
    expect(page.locator('#track-title')).to_have_text('Second track')
    page.locator('#previous').click()
    expect(page.locator('#track-title')).to_have_text('Local track')
    page.wait_for_function('() => document.querySelector("audio").readyState >= 2')
    page.evaluate('document.querySelector("audio").currentTime = 7.7')
    expect(page.locator('#track-title')).to_have_text('Second track', timeout=10000)
    page.wait_for_function('() => document.querySelector("audio").readyState >= 2')
    page.evaluate('document.querySelector("audio").pause(); document.querySelector("audio").currentTime = 2')
    page.wait_for_function('() => JSON.parse(localStorage.getItem("migi.music.v1")).time >= 1.9')
    page.reload()
    expect(page.locator('#track-title')).to_have_text('Second track')
    page.wait_for_function('() => document.querySelector("audio").currentTime >= 1.9')
    assert page.evaluate('document.querySelector("audio").paused')
    # Remote audio goes through the actual origin request/upload relay.
    page.get_by_role('button', name='Remote album').click()
    expect(page.locator('#track-title')).to_have_text('Remote track')
    page.wait_for_function('() => !document.querySelector("audio").paused && document.querySelector("audio").currentTime > 0.1')
    page.evaluate('document.querySelector("audio").currentTime = 5')
    page.wait_for_function('() => document.querySelector("audio").currentTime >= 5')
    page.evaluate('document.querySelector("audio").pause()')
    expect(page.locator('#music-error')).to_be_hidden()
    page.screenshot(path=str(output / 'desktop.png'), full_page=True)
    page.locator('#show-tracks').click()
    expect(page.locator('#library-list button')).to_have_count(3)
    page.locator('#search').fill('Second')
    expect(page.locator('#library-list button')).to_have_count(1)
    page.locator('#library-list button').click()
    expect(page.locator('#track-title')).to_have_text('Second track')
    expect(page.locator('#queue-list button')).to_have_count(1)
    page.evaluate('document.querySelector("audio").pause()')
    page.set_viewport_size({'width': 390, 'height': 844})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.screenshot(path=str(output / 'mobile.png'), full_page=True)
    # A failed stream and failed catalog refresh have visible, recoverable errors.
    page.route('**/api/media/*', lambda route: route.fulfill(status=503, body='offline'))
    page.locator('#queue-list button').click()
    expect(page.locator('#music-error')).to_be_visible()
    page.unroute('**/api/media/*')
    page.locator('#queue-list button').click()
    page.wait_for_function('() => !document.querySelector("audio").paused && document.querySelector("audio").currentTime > 0.1')
    expect(page.locator('#music-error')).to_be_hidden()
    page.route('**/api/library', lambda route: route.fulfill(status=503, body='offline'))
    page.locator('#refresh').click()
    expect(page.locator('#music-error')).to_contain_text('503')
    page.unroute('**/api/library')
    page.locator('#refresh').click()
    expect(page.locator('#music-error')).to_be_hidden()
    assert not errors, errors
    browser.close()
print(f'PASS: local/origin playback, pause, seek, queue, auto-next, restore, search, errors, mobile. Screenshots: {output}')
